minimum_pre_commit_version: 1.18.0
default_language_version: {}
default_stages: [ commit ]
repos:
    -   repo: https://github.com/Yelp/detect-secrets
        rev: v0.13.0
        hooks:
        -   id: detect-secrets
            args: ['--baseline', '.secrets.baseline']
            exclude: .*/tests/.*
