{% set name = "gbdxtools" %}
{% set version = "0.17.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 449f727f43d2eb9dddf8472f7b39265073e0510c5a48b01615fc84d67816f0d4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - pytest-runner
    - python
    - vcrpy
    - moto
  run:
    - python
    - affine
    - requests >=2.12.1
    - imageio
    - tifffile
    - shapely
    - boto3
    - dask-core >=2.0.0 
    - numpy >=1.14
    - ephem
    - gbdx-auth >=0.2.6
    - mercantile >=0.10.0
    - mock
    - pyproj
    - pytest
    - pytest-runner
    - vcrpy

test:
  imports:
    - gbdxtools
    - gbdxtools.images
    - gbdxtools.images.drivers
    - gbdxtools.images.exceptions
    - gbdxtools.images.mixins
    - gbdxtools.images.util
    - gbdxtools.rda
  requires:
    - pytest
    - vcrpy
    - python
    - pytest-runner
    - moto

about:
  home: https://github.com/DigitalGlobe/gbdxtools
  license: MIT
  license_family: MIT
  summary: API wrapper and imagery access for the GBDX Platform
  doc_url: https://gbdxtools.readthedocs.io

extra:
  recipe-maintainers:
    - drwelby
