{% set data = load_setup_py_data() %}

package:
  name: gbdxtools
  version: {{ data.get('version') }}

build:
  build: 0
  script: pip install .
  noarch: python

source:
  git_url: ./

requirements:
  run:
    - python
    - six >=1.10.0
    - future >=0.15.2
    - requests >=2.12.1
    - boto >=2.47.0
    - shapely
    - ephem
    - toolz
    - cloudpickle
    - dask ==0.15.2
    - numpy
    - pycurl
    - rasterio >=0.36.0
    - pyproj
    - requests-futures
    - configparser
    - mercantile >=0.10.0
    - scikit-image
    - gbdx-auth ==0.2.4
    - jpeg ==8d
    - cachetools >=2.0.0 # py27

  build:
    - setuptools
    - python
    - six >=1.10.0
    - future >=0.15.2
    - requests >=2.12.1
    - boto >=2.47.0
    - shapely
    - ephem
    - toolz
    - cloudpickle
    - dask ==0.15.2
    - {{ pin_compatible('numpy', min_pin='1.9') }}
    - pycurl
    - rasterio >=0.36.0
    - pyproj
    - requests-futures
    - configparser
    - mercantile >=0.10.0
    - scikit-image
    - gbdx-auth ==0.2.4
    - bumpversion
    - pytest
    - pytest-runner
    - vcrpy
    - jpeg ==8d
    - cachetools >=2.0.0
