{% set name = "gbdxtools" %}
{% set version = "0.17.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26b1f7e0ccd6ae52868cf350587a8f7fdf883ab1acf8decb11cefe241f4e04ec 

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - pytest-runner
    - python
    - vcrpy
    - moto
  run:
    - affine
    - boto3
    - bumpversion
    - cachetools >=2.0.0
    - cloudpickle
    - configparser
    - dask-core >=2.0.0 
    - ephem
    - future >=0.15.2
    - gbdx-auth >=0.2.6
    - mercantile >=0.10.0
    - mock
    - numpy >=1.14
    - pycurl
    - pyproj
    - pytest
    - pytest-runner
    - python
    - requests >=2.12.1
    - requests-futures
    - imageio
    - tifffile
    - shapely
    - six >=1.10.0
    - toolz
    - vcrpy

test:
  imports:
    - gbdxtools
    - gbdxtools.images
    - gbdxtools.images.drivers
    - gbdxtools.images.exceptions
    - gbdxtools.images.mixins
    - gbdxtools.images.util
    - gbdxtools.rda
  requires:
    - pytest
    - vcrpy
    - python
    - pytest-runner
    - moto

about:
  home: https://github.com/DigitalGlobe/gbdxtools
  license: MIT
  license_family: MIT
  summary: API wrapper and imagery access for the GBDX Platform
  doc_url: https://gbdxtools.readthedocs.io

extra:
  recipe-maintainers:
    - drwelby
